package antonafanasjew.cosmodog;

public enum InputHandlerType {

	INPUT_HANDLER_NO_INPUT,
	INPUT_HANDLER_INGAME_CONTROL,
	INPUT_HANDLER_INGAME,
	INPUT_HANDLER_INGAME_DIALOG,
	INPUT_HANDLER_INGAME_DEBUGCONSOLE,
	INPUT_HANDLER_INGAME_TEXTFRAME;
	
}
